"""Prompt templates (DESIGN.md §5, §9)."""

from twin.prompts.templates import (
    CREATOR_SYSTEM,
    JUDGE_SYSTEM,
    PERSONAS,
    SOLVER_CODE_SYSTEM,
    SOLVER_LOGIC_SYSTEM,
    SOLVER_SYSTEM,
    THEMES,
    creator_persona,
    creator_problem_user,
    creator_system,
    creator_user,
    is_code_problem,
    is_logic_problem,
    opponent_of,
    persona_of,
    pick_theme,
    solver_persona,
    solver_system,
    solver_user,
)

__all__ = [
    "CREATOR_SYSTEM",
    "JUDGE_SYSTEM",
    "PERSONAS",
    "SOLVER_CODE_SYSTEM",
    "SOLVER_LOGIC_SYSTEM",
    "SOLVER_SYSTEM",
    "THEMES",
    "creator_persona",
    "creator_problem_user",
    "creator_system",
    "creator_user",
    "is_code_problem",
    "is_logic_problem",
    "opponent_of",
    "persona_of",
    "pick_theme",
    "solver_persona",
    "solver_system",
    "solver_user",
]
